//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMonitorService.DataUpdateProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DataUpdateProxy.IDataUpdateService")]
    public interface IDataUpdateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataUpdateService/UpdateData", ReplyAction="http://tempuri.org/IDataUpdateService/UpdateDataResponse")]
        bool UpdateData(System.Data.DataSet name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataUpdateService/UpdateData", ReplyAction="http://tempuri.org/IDataUpdateService/UpdateDataResponse")]
        System.Threading.Tasks.Task<bool> UpdateDataAsync(System.Data.DataSet name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataUpdateService/SayHello", ReplyAction="http://tempuri.org/IDataUpdateService/SayHelloResponse")]
        bool SayHello(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDataUpdateService/SayHello", ReplyAction="http://tempuri.org/IDataUpdateService/SayHelloResponse")]
        System.Threading.Tasks.Task<bool> SayHelloAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataUpdateServiceChannel : DataMonitorService.DataUpdateProxy.IDataUpdateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataUpdateServiceClient : System.ServiceModel.ClientBase<DataMonitorService.DataUpdateProxy.IDataUpdateService>, DataMonitorService.DataUpdateProxy.IDataUpdateService {
        
        public DataUpdateServiceClient() {
        }
        
        public DataUpdateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataUpdateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataUpdateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataUpdateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool UpdateData(System.Data.DataSet name) {
            return base.Channel.UpdateData(name);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateDataAsync(System.Data.DataSet name) {
            return base.Channel.UpdateDataAsync(name);
        }
        
        public bool SayHello(string name) {
            return base.Channel.SayHello(name);
        }
        
        public System.Threading.Tasks.Task<bool> SayHelloAsync(string name) {
            return base.Channel.SayHelloAsync(name);
        }
    }
}
